"""
CAM Section Draft Generator.

Generates AI-drafted text sections for the structured Credit Appraisal Memorandum.
Each section is labelled and returned as a dict for the RM to review and edit.

Sections generated by AI:
  - company_background
  - group_structure
  - management_profile
  - business_model
  - industry_analysis
  - financial_analysis
  - working_capital
  - key_issues
  - recommendation
  - executive_summary   (generated last — synthesises all other sections)

Sections that are manual (RM-filled) — NOT generated:
  - banking_arrangement  (type, bank table)
  - account_conduct      (free text)
"""
import os
import re
import logging
import httpx
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

# ── Delimiter used to split sections ──────────────────────────────────────────
_DELIM = "###SECTION:"

AI_SECTIONS = [
    "company_background",
    "group_structure",
    "management_profile",
    "business_model",
    "industry_analysis",
    "financial_analysis",
    "working_capital",
    "banking_arrangement",
    "proposed_structure",
    "peer_comparison",
    "key_issues",
    "recommendation",
    "executive_summary",   # generated last — synthesises all others
]

SECTION_PROMPTS = {
    "company_background": (
        "Write 2-3 paragraphs on the company's background: date of incorporation, "
        "registered office, nature of business, key business segments, "
        "milestones/major events. Use only facts from the data provided."
    ),
    "group_structure": (
        "Describe the group/corporate structure: parent company (if any), "
        "key subsidiaries and associates, cross-holdings, group turnover (if inferable). "
        "If no group data is available, state 'Standalone entity — no major subsidiaries identified'."
    ),
    "management_profile": (
        "Describe the promoter/management team using ONLY names and facts explicitly stated in "
        "the COMPANY INFO, KEY POINTS, or WEB RESEARCH BRIEF sections of the context. "
        "DO NOT invent, assume, or guess promoter names, family names, or biographical details "
        "that are not present in the provided data — if names are absent, write "
        "'Promoter names and KYC details to be verified from latest BSE/NSE shareholding pattern "
        "and RoC filings as part of due diligence.' "
        "Cover: (a) promoter holding percentage (use the exact figure from context), "
        "(b) any management quality signals inferred from financial performance or research brief, "
        "(c) board composition comments if inferable, "
        "(d) PEP screening note. "
        "Flag if any Politically Exposed Person (PEP) indicators are present."
    ),
    "business_model": (
        "Explain the company's business model: how it generates revenue, "
        "key customers/markets, supply chain, competitive positioning, "
        "key contracts or clients (if inferable). Reference the industry and "
        "company information provided."
    ),
    "industry_analysis": (
        "Analyse the industry context: sector growth trends, key demand drivers, "
        "competitive intensity, regulatory environment, raw material/input cost dynamics, "
        "and tailwinds/headwinds for the borrower's specific industry segment."
    ),
    "key_issues": (
        "Identify 4-6 key credit issues and risks specific to this borrower: "
        "financial risks (leverage, coverage), operational risks, industry risks, "
        "management/governance risks, and any specific red flags from the data. "
        "Format each as: **Issue N: [Title]** — [2-3 sentence explanation with evidence]."
    ),
    "recommendation": (
        "Write a credit recommendation: state whether to recommend approval/decline/further review, "
        "suggested loan amount (if applicable), key conditions precedent, "
        "financial covenants to impose, and monitoring requirements. "
        "Base the recommendation strictly on the financial and qualitative data provided."
    ),
    "financial_analysis": (
        "Write a formal financial analysis section in 4-5 paragraphs covering:\n"
        "1. Revenue & profitability trend: cite exact ₹ figures for each year, revenue CAGR, "
        "EBITDA margin expansion/contraction, PAT trajectory. Flag any anomalous jumps and request audit confirmation.\n"
        "2. Leverage & coverage: cite Debt/Equity, Debt/EBITDA, and Interest Coverage ratio for each year from the CMA table. "
        "State whether coverage meets the bank benchmark (ICR > 1.5x minimum, > 3.0x comfortable).\n"
        "3. DSCR analysis: cite the computed DSCR values for actuals and projections from the CMA table. "
        "State clearly whether DSCR exceeds the minimum threshold of 1.25x for term loan eligibility. "
        "Explain the components (PAT + Dep + Interest) / (Principal + Interest).\n"
        "4. TOL/TNW and FACR: cite values from the CMA table. "
        "TOL/TNW benchmark is <3.0x; FACR benchmark is >1.25x. Comment on adequacy.\n"
        "5. Stress scenario: briefly describe what happens to DSCR if revenue falls 15% or EBITDA margin compresses 5 pp.\n"
        "Use exact figures from the FINANCIALS table and CMA PROJECTED FINANCIALS table in the context. "
        "Reference specific numbers — do not use vague language like 'strong' without citing the figure."
    ),
    "working_capital": (
        "Analyse the working capital position: describe the operating cycle length, "
        "key components (inventory days, debtor days, creditor days), adequacy of working capital limits, "
        "drawing power assessment based on current assets, and any concerns around WC utilisation patterns. "
        "Use only data available; flag areas requiring stock statement verification."
    ),
    "executive_summary": (
        "Write a concise executive summary (maximum 1 page) covering: borrower name and proposed facility, "
        "business overview in 2–3 sentences, key financial highlights (revenue, PAT, DSCR, leverage), "
        "credit strengths, top 2–3 risk factors, and the recommended credit decision. "
        "This is the first section a credit committee member will read — make it crisp and decisive."
    ),
    "banking_arrangement": (
        "Generate a structured Banking Arrangement section for a Credit Appraisal Memorandum. "
        "Include:\n"
        "1. A markdown table of the borrower's existing credit facilities with ALL banks, with columns: "
        "Bank Name | Facility Type | Sanctioned Limit (₹ Cr) | Outstanding (₹ Cr) | Security | Remarks. "
        "If specific details are not available in the data, use '[To be obtained]' as placeholder — DO NOT fabricate figures.\n"
        "2. Account conduct summary: any instances of irregularity, bounced instruments, overutilisation.\n"
        "3. CIBIL/CMR score and status (use '[To be verified]' if not available).\n"
        "4. Total banking system exposure (sum across all lenders).\n"
        "5. One paragraph on the proposed bank's relationship with the borrower if any.\n"
        "Use a professional formal tone. Flag clearly what information is pending."
    ),
    "proposed_structure": (
        "Generate the Proposed Credit Facility Structure section. Include:\n"
        "1. Facility details: Type (Working Capital — Cash Credit/Overdraft), Amount (₹ Cr), Tenor, "
        "Purpose, Disbursement mode.\n"
        "2. Drawing Power (DP) Calculation using Indian banking norms (Tandon Committee Method II):\n"
        "   Present a markdown table:\n"
        "   | Item | Amount (₹ Cr) |\n"
        "   | Inventory (at cost) | [value or 'As per stock statement'] |\n"
        "   | Trade Receivables (< 90 days) | [value or 'As per debtor ageing'] |\n"
        "   | Other Current Assets | [value] |\n"
        "   | **Total Current Assets (A)** | [total] |\n"
        "   | Less: Trade Creditors | [value] |\n"
        "   | Less: Other Current Liabilities | [value] |\n"
        "   | **Total Current Liabilities excl. Bank Borrowings (B)** | [total] |\n"
        "   | **Working Capital Gap (A-B)** | [gap] |\n"
        "   | Bank Financing (75% of WCG — Method II) | [75% of gap] |\n"
        "   | **Drawing Power (min of Bank Financing & Limit)** | [DP] |\n"
        "   Use actual balance sheet figures where available. Flag '[Requires stock statement]' where live data is needed.\n"
        "3. Security structure:\n"
        "   - Primary: Hypothecation of entire current assets (stock, book debts) — first charge\n"
        "   - Collateral: [as applicable]\n"
        "   - Guarantee: Corporate/personal guarantee if applicable\n"
        "4. Pricing: Interest rate (Base Rate / MCLR + spread), processing fee, review frequency.\n"
        "5. Repayment: For WC — annual review; for term — EMI schedule.\n"
        "Use actual financial data from the context where available."
    ),
    "peer_comparison": (
        "Write a Peer Comparison section with:\n"
        "1. A markdown table comparing the borrower against 3-4 named peer companies on these metrics:\n"
        "   Company | Revenue (₹ Cr) | EBITDA Margin % | PAT Margin % | D/E Ratio | Interest Coverage | ROCE % | Credit Rating\n"
        "   Use the peer list and financial data provided. If peer financials are not in the data, "
        "   use approximate publicly known figures with a note '(approximate)'.\n"
        "2. A 2-3 sentence narrative on how the borrower compares to peers — strengths and gaps.\n"
        "3. Industry median benchmarks for the sector where available.\n"
        "Base this on the sector and peers provided in the context."
    ),
}


# ── LLM helpers ───────────────────────────────────────────────────────────────

def _ollama_call(prompt: str) -> str:
    url   = os.getenv("OLLAMA_URL", "http://localhost:11434")
    model = os.getenv("OLLAMA_MODEL", "qwen3:8b")
    try:
        resp = httpx.post(
            f"{url}/v1/chat/completions",
            json={
                "model": model,
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are a senior credit risk analyst at an Indian commercial bank. "
                            "Write formal, concise, banker-grade credit appraisal sections. "
                            "Use ONLY the data provided. Do NOT fabricate figures. "
                            "Do NOT include any <think> tags or reasoning traces. "
                            "Output ONLY the requested section text in plain prose (no extra headings)."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
                "stream": False,
            },
            timeout=300.0,
        )
        resp.raise_for_status()
        text = resp.json()["choices"][0]["message"]["content"].strip()
        return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    except Exception as e:
        logger.error(f"Ollama call error: {e}")
        return ""


def _gemini_call(prompt: str) -> str:
    try:
        from google import genai
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            return ""
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="models/gemini-flash-lite-latest",
            contents=prompt,
        )
        return response.text.strip()
    except Exception as e:
        logger.error(f"Gemini call error: {e}")
        return ""


def _claude_call(prompt: str) -> str:
    """Call Claude via the `claude` CLI (uses Claude Code Pro subscription — no API key needed)."""
    import subprocess
    system = (
        "You are a senior credit risk analyst at an Indian commercial bank. "
        "Write formal, concise, banker-grade credit appraisal sections. "
        "Use ONLY the data provided. Do NOT fabricate figures. "
        "Output ONLY the requested section text in plain prose (no extra headings)."
    )
    full_prompt = f"{system}\n\n{prompt}"
    try:
        result = subprocess.run(
            ["claude", "-p", full_prompt],
            capture_output=True,
            text=True,
            timeout=300,
        )
        if result.returncode != 0:
            logger.error(f"Claude CLI error: {result.stderr}")
            return ""
        return result.stdout.strip()
    except Exception as e:
        logger.error(f"Claude CLI call error: {e}")
        return ""


def _llm(prompt: str) -> str:
    provider = os.getenv("MEMO_PROVIDER", "gemini").lower()
    if provider == "claude":
        result = _claude_call(prompt)
        if result:
            return result
        logger.warning("Claude CLI unavailable, falling back to Gemini")
        result = _gemini_call(prompt)
        if result:
            return result
    elif provider == "gemini":
        result = _gemini_call(prompt)
        if result:
            return result
        logger.warning("Gemini failed, falling back to Ollama")
    result = _ollama_call(prompt)
    if result:
        return result
    logger.warning("Ollama failed, falling back to Gemini")
    return _gemini_call(prompt)


# ── Context builder ───────────────────────────────────────────────────────────

def _fmt(v, decimals=2):
    """Format a number or return 'N/A'."""
    if v is None:
        return "N/A"
    try:
        return f"{float(v):,.{decimals}f}"
    except (TypeError, ValueError):
        return str(v)


def _build_context_text(financials: Dict, ratios: Dict, company_name: str, research_brief: str) -> str:
    lines = [f"COMPANY: {company_name}"]

    ci = financials.get("company_info", {})
    if ci.get("industry"):
        lines.append(f"INDUSTRY: {ci['industry']}")
    if ci.get("about") or ci.get("description"):
        lines.append(f"ABOUT: {(ci.get('about') or ci.get('description', ''))[:400]}")
    if ci.get("key_points"):
        lines.append("KEY POINTS: " + " | ".join(str(x) for x in ci["key_points"][:6]))

    pl = financials.get("profit_loss", {})
    bs = financials.get("balance_sheet", {})
    cf = financials.get("cash_flow", {})

    years  = pl.get("years", [])
    rev    = pl.get("revenue", [])
    pat    = pl.get("pat", [])
    ebitda = pl.get("ebitda", [])
    pbt    = pl.get("pbt", [])
    interest = pl.get("interest", []) or pl.get("finance_costs", [])
    dep    = pl.get("depreciation", [])

    bs_years = bs.get("years", years)
    borrowings = bs.get("borrowings", [])
    total_equity = bs.get("total_equity", [])
    total_assets = bs.get("total_assets", [])

    # Normalise to lists
    def _to_list(x):
        return x if isinstance(x, list) else []

    rev = _to_list(rev); pat = _to_list(pat); ebitda = _to_list(ebitda)
    pbt = _to_list(pbt); interest = _to_list(interest); dep = _to_list(dep)
    borrowings = _to_list(borrowings); total_equity = _to_list(total_equity)
    total_assets = _to_list(total_assets)

    if years:
        # ── Multi-year financial table ────────────────────────────────────────
        col_w = 14
        header = "Metric".ljust(28) + "".join(str(y).rjust(col_w) for y in years)
        sep = "-" * (28 + col_w * len(years))
        table_rows = ["\nFINANCIALS (₹ Crore):", sep, header, sep]

        def row(label, arr):
            return label.ljust(28) + "".join(_fmt(arr[i] if i < len(arr) else None).rjust(col_w) for i in range(len(years)))

        table_rows.append(row("Revenue from Operations", rev))
        table_rows.append(row("EBITDA", ebitda))

        # EBITDA margin %
        ebitda_margins = []
        for i in range(len(years)):
            r_v = rev[i] if i < len(rev) else None
            e_v = ebitda[i] if i < len(ebitda) else None
            m = round(e_v / r_v * 100, 1) if r_v and e_v and r_v > 0 else None
            ebitda_margins.append(m)
        table_rows.append(row("EBITDA Margin %", ebitda_margins))
        table_rows.append(row("Profit Before Tax", pbt))
        table_rows.append(row("Profit After Tax (PAT)", pat))

        # PAT margin %
        pat_margins = []
        for i in range(len(years)):
            r_v = rev[i] if i < len(rev) else None
            p_v = pat[i] if i < len(pat) else None
            m = round(p_v / r_v * 100, 1) if r_v and p_v and r_v > 0 else None
            pat_margins.append(m)
        table_rows.append(row("PAT Margin %", pat_margins))
        table_rows.append(row("Finance Costs", interest))
        table_rows.append(row("Depreciation", dep))
        table_rows.append(sep)
        table_rows.append(row("Total Assets", total_assets))
        table_rows.append(row("Total Borrowings", borrowings))
        table_rows.append(row("Total Equity / Net Worth", total_equity))

        # D/E ratio
        de_ratios = []
        for i in range(len(years)):
            b = borrowings[i] if i < len(borrowings) else None
            e = total_equity[i] if i < len(total_equity) else None
            de_ratios.append(round(b / e, 2) if b is not None and e and e > 0 else None)
        table_rows.append(row("Debt / Equity Ratio", de_ratios))

        # Interest coverage
        icr_series = []
        for i in range(len(years)):
            eb = ebitda[i] if i < len(ebitda) else None
            fi = interest[i] if i < len(interest) else None
            icr_series.append(round(eb / fi, 2) if eb and fi and fi > 0 else None)
        table_rows.append(row("Interest Coverage (x)", icr_series))

        # ── DSCR: approximate PAT from EPS × shares (91 Cr shares for Lupin-class)
        # DSCR = (PAT + Depreciation) / (Principal Repayment + Interest)
        # We approximate PAT from PBT × 0.75 when PAT list not numeric.
        # For projections we assume ~5 yr term loan, equal annual principal.
        eps_list = _to_list(pl.get("eps", []))
        shares_cr = float(bs.get("equity_capital", [0])[-1] or 0) / 10.0  # face value ₹10
        pat_approx = []
        for i in range(len(years)):
            p = None
            if i < len(pat) and isinstance(pat[i], (int, float)):
                p = pat[i]
            elif i < len(eps_list) and isinstance(eps_list[i], (int, float)) and shares_cr > 0:
                p = eps_list[i] * shares_cr
            elif i < len(pbt) and isinstance(pbt[i], (int, float)):
                p = pbt[i] * 0.75  # approximate tax at 25%
            pat_approx.append(p)
        table_rows.append(row("PAT (approx.)", pat_approx))

        # DSCR assuming proposed ₹500 Cr term loan / 5 years = ₹100 Cr annual principal
        proposed_principal_repayment = 100.0  # ₹ Cr/year (conservative; adjust per deal)
        dscr_series = []
        for i in range(len(years)):
            p = pat_approx[i]
            d = dep[i] if i < len(dep) else None
            fi = interest[i] if i < len(interest) else None
            if p is not None and d is not None and fi is not None:
                tds = proposed_principal_repayment + fi
                dscr_val = round((p + d + fi) / tds, 2) if tds > 0 else None
                dscr_series.append(dscr_val)
            else:
                dscr_series.append(None)
        table_rows.append(row("DSCR (proposed TL, est.)", dscr_series))

        # TOL/TNW = (Total Liabilities – Total Equity) / Total Equity
        tol_tnw_series = []
        for i in range(len(years)):
            ta = total_assets[i] if i < len(total_assets) else None
            te = total_equity[i] if i < len(total_equity) else None
            if ta is not None and te and te > 0:
                tol = ta - te
                tol_tnw_series.append(round(tol / te, 2))
            else:
                tol_tnw_series.append(None)
        table_rows.append(row("TOL / TNW (x)", tol_tnw_series))

        # FACR = Net Fixed Assets / Term Loan Outstanding (at end of each year)
        fixed_assets_list = _to_list(bs.get("fixed_assets", []))
        facr_series = []
        outstanding_tl = 500.0  # proposed at inception
        for i in range(len(years)):
            nfa = fixed_assets_list[i] if i < len(fixed_assets_list) else None
            if nfa is not None and outstanding_tl > 0:
                facr_series.append(round(nfa / outstanding_tl, 2))
            else:
                facr_series.append(None)
            outstanding_tl = max(0.0, outstanding_tl - proposed_principal_repayment)
        table_rows.append(row("FACR (NFA / TL Outst.)", facr_series))

        table_rows.append(sep)
        lines.extend(table_rows)

        # ── 2-year forward projections (conservative: 50% of historical revenue CAGR) ──
        if len(years) >= 2 and rev and rev[-1]:
            n = len(years) - 1
            hist_rev_cagr = ((rev[-1] / rev[0]) ** (1 / n) - 1) if rev[0] and rev[0] > 0 else 0.10
            proj_g = min(hist_rev_cagr * 0.5, 0.15)  # cap at 15%, 50% of historical
            last_rev = rev[-1]
            last_ebitda_margin = (ebitda[-1] / rev[-1]) if ebitda and ebitda[-1] and rev[-1] else 0.25
            # Use last year as base for projections
            last_dep = dep[-1] if dep else 600
            last_int = interest[-1] if interest else 100
            last_borr = borrowings[-1] if borrowings else 250
            last_equity = total_equity[-1] if total_equity else 24000
            last_assets = total_assets[-1] if total_assets else 28000
            last_nfa = fixed_assets_list[-1] if fixed_assets_list else 4500

            proj_lines = ["\nCMA FORMAT — PROJECTED FINANCIALS (Conservative, indicative only):"]
            proj_sep = "-" * (28 + 14 * 2)
            last_yr_str = years[-1] if years else "FY2025"
            proj_years = [f"P1 ({last_yr_str[:2]}{int(last_yr_str[-2:])+1}E)",
                          f"P2 ({last_yr_str[:2]}{int(last_yr_str[-2:])+2}E)"]
            proj_header = "Metric".ljust(28) + "".join(y.rjust(14) for y in proj_years)
            proj_lines.append(proj_sep)
            proj_lines.append(proj_header)
            proj_lines.append(proj_sep)

            p_rev = [round(last_rev * (1 + proj_g), 1), round(last_rev * (1 + proj_g) ** 2, 1)]
            p_ebitda = [round(r * last_ebitda_margin, 1) for r in p_rev]
            p_dep = [round(last_dep * 1.05, 1), round(last_dep * 1.10, 1)]
            p_int = [round(last_int + proposed_principal_repayment * 0.08, 1),
                     round(last_int + proposed_principal_repayment * 0.06, 1)]
            p_pbt = [round(p_ebitda[i] - p_dep[i] - p_int[i], 1) for i in range(2)]
            p_pat = [round(x * 0.75, 1) for x in p_pbt]
            p_borr = [round(last_borr + 500 - proposed_principal_repayment * (i + 1), 1) for i in range(2)]
            p_equity = [round(last_equity + p_pat[0], 1), round(last_equity + p_pat[0] + p_pat[1], 1)]
            p_assets = [round(last_assets + p_pat[0], 1), round(last_assets + p_pat[0] + p_pat[1], 1)]
            p_nfa = [round(last_nfa * 1.05, 1), round(last_nfa * 1.08, 1)]
            p_de = [round(p_borr[i] / p_equity[i], 3) for i in range(2)]
            p_icr = [round(p_ebitda[i] / p_int[i], 2) if p_int[i] > 0 else None for i in range(2)]
            p_tds = [proposed_principal_repayment + p_int[i] for i in range(2)]
            p_dscr = [round((p_pat[i] + p_dep[i] + p_int[i]) / p_tds[i], 2) if p_tds[i] > 0 else None for i in range(2)]
            p_tol = [round((p_assets[i] - p_equity[i]) / p_equity[i], 2) for i in range(2)]
            p_facr_outstd = [500 - proposed_principal_repayment * (i + 1) for i in range(2)]
            p_facr = [round(p_nfa[i] / p_facr_outstd[i], 2) if p_facr_outstd[i] > 0 else None for i in range(2)]

            def prow(label, arr):
                return label.ljust(28) + "".join(_fmt(v).rjust(14) for v in arr)

            proj_lines.append(prow("Revenue from Operations", p_rev))
            proj_lines.append(prow("EBITDA", p_ebitda))
            proj_lines.append(prow("EBITDA Margin %", [round(p_ebitda[i]/p_rev[i]*100,1) for i in range(2)]))
            proj_lines.append(prow("Depreciation", p_dep))
            proj_lines.append(prow("Finance Costs", p_int))
            proj_lines.append(prow("PBT", p_pbt))
            proj_lines.append(prow("PAT (est. @ 75% of PBT)", p_pat))
            proj_lines.append(proj_sep)
            proj_lines.append(prow("Total Borrowings", p_borr))
            proj_lines.append(prow("Total Equity / Net Worth", p_equity))
            proj_lines.append(prow("Net Fixed Assets", p_nfa))
            proj_lines.append(proj_sep)
            proj_lines.append(prow("Debt / Equity (x)", p_de))
            proj_lines.append(prow("Interest Coverage (x)", p_icr))
            proj_lines.append(prow("DSCR (proposed TL)", p_dscr))
            proj_lines.append(prow("TOL / TNW (x)", p_tol))
            proj_lines.append(prow("FACR (NFA / TL Outst.)", p_facr))
            proj_lines.append(proj_sep)
            proj_lines.append(f"Note: Projections assume {round(proj_g*100,1)}% revenue growth (50% of {round(hist_rev_cagr*100,1)}% historical CAGR).")
            proj_lines.append(f"      Annual TL principal repayment assumed at ₹{proposed_principal_repayment:.0f} Cr (₹500 Cr / 5 years).")
            proj_lines.append("      DSCR benchmark: >1.25x. FACR benchmark: >1.25x. TOL/TNW benchmark: <3.0x.")
            lines.extend(proj_lines)

        # CAGR summary
        if len(years) >= 2:
            n = len(years) - 1
            if rev and rev[0] and rev[-1] and rev[0] > 0:
                cagr = round(((rev[-1] / rev[0]) ** (1 / n) - 1) * 100, 1)
                lines.append(f"Revenue CAGR ({n}yr): {cagr}%")
            if pat_approx and pat_approx[0] and pat_approx[-1] and pat_approx[0] > 0 and pat_approx[-1] > 0:
                cagr = round(((pat_approx[-1] / pat_approx[0]) ** (1 / n) - 1) * 100, 1)
                lines.append(f"PAT CAGR ({n}yr): {cagr}%")

        # Cash flow summary
        cfo_years = cf.get("years", [])
        cfo_vals = cf.get("operating", [])
        if cfo_years and cfo_vals:
            lines.append("Operating Cash Flow (₹ Cr): " +
                         ", ".join(f"{y}: {_fmt(v)}" for y, v in zip(cfo_years, cfo_vals)))

    else:
        # Single-year fallback
        rev_d = pl.get("revenue", {})
        if isinstance(rev_d, dict):
            rv = rev_d.get("revenue_from_operations") or rev_d.get("total_income")
            lines.append(f"\nREVENUE: ₹{_fmt(rv)} Cr")
        pm = pl.get("profit_metrics", {})
        if isinstance(pm, dict):
            lines.append(f"PAT: ₹{_fmt(pm.get('profit_after_tax'))} Cr | EBITDA: ₹{_fmt(pm.get('ebitda'))} Cr")

        eq = bs.get("equity", {})
        if isinstance(eq, dict) and eq.get("total_equity"):
            lines.append(f"NET WORTH: ₹{_fmt(eq['total_equity'])} Cr")

    # Screener ratios if available
    screener_ratios = financials.get("key_ratios_from_screener", {})
    if screener_ratios:
        lines.append("\nKEY RATIOS (Screener):")
        for k, v in screener_ratios.items():
            if v is not None and not isinstance(v, list):
                lines.append(f"  {k}: {v}")

    # Computed ratios
    key_ratios = {
        "Debt/Equity": ratios.get("debt_equity"),
        "Current Ratio": ratios.get("current_ratio"),
        "Interest Coverage (x)": ratios.get("interest_coverage"),
        "DSCR": ratios.get("dscr"),
        "EBITDA Margin %": ratios.get("ebitda_margin"),
        "ROCE %": ratios.get("roce"),
        "Debtor Days": screener_ratios.get("debtor_days") or ratios.get("debtor_days"),
        "Inventory Days": screener_ratios.get("inventory_days") or ratios.get("inventory_days"),
        "Creditor Days": screener_ratios.get("payable_days") or ratios.get("payable_days"),
    }
    kr_lines = [f"  {k}: {v}" for k, v in key_ratios.items() if v is not None]
    if kr_lines:
        lines.append("\nCOMPUTED RATIOS:\n" + "\n".join(kr_lines))

    # Shareholding
    sh = financials.get("shareholding", {})
    prom = sh.get("promoter_holding_pct") or financials.get("company_info", {}).get("promoter_holding")
    if prom:
        lines.append(f"\nPROMOTER HOLDING: {prom}%")
        trend = sh.get("promoter_trend", [])
        if trend:
            lines.append("Promoter trend: " + ", ".join(f"{t['period']}: {t['pct']}%" for t in trend[-4:]))

    # Peers
    peers = financials.get("peers", [])
    if peers:
        lines.append(f"\nPEER COMPANIES: {', '.join(str(p.get('Name', p.get('name', str(p)))) for p in peers[:5])}")

    # Credit ratings
    ratings = financials.get("company_info", {}).get("credit_ratings", [])
    if ratings:
        lines.append("\nCREDIT RATINGS: " + " | ".join(str(r) for r in ratings[:3]))

    if research_brief:
        lines.append(f"\nWEB RESEARCH BRIEF:\n{research_brief[:4000]}")

    return "\n".join(lines)


# ── Per-section generation ────────────────────────────────────────────────────

def _draft_section(
    section_key: str,
    context_text: str,
    company_name: str,
    extra_brief: str = "",
) -> str:
    instruction = SECTION_PROMPTS.get(section_key, "Write a brief analysis for this section.")
    prompt = f"""{context_text}

{'---\nADDITIONAL CONTEXT:\n' + extra_brief if extra_brief else ''}

---
TASK: For borrower "{company_name}", write the **{section_key.replace('_', ' ').title()}** section of the Credit Appraisal Memorandum.

{instruction}

Write in formal banker prose. 2-4 paragraphs unless the instruction says otherwise.
Output ONLY the section content — no headings, no preamble."""
    return _llm(prompt)


# ── Batch generation via a single LLM call ───────────────────────────────────

def _draft_all_sections_batch(
    context_text: str,
    company_name: str,
    sections: list = None,
) -> Dict[str, str]:
    """
    One LLM call to generate all AI sections separated by delimiters.
    Fallback: generate each section individually.
    """
    target = sections if sections is not None else AI_SECTIONS
    section_list = "\n".join(
        f"{_DELIM}{k}###\n{SECTION_PROMPTS[k]}"
        for k in target if k in SECTION_PROMPTS
    )
    prompt = f"""{context_text}

---
You are writing a Credit Appraisal Memorandum for "{company_name}".
Generate ALL sections below. Each section must start with its delimiter exactly as shown.

{section_list}

RULES:
- Use ONLY the data provided above. Do NOT fabricate any figures.
- Each section: 2-4 paragraphs of formal banker prose.
- Do NOT add extra headings inside sections.
- Do NOT output any <think> tags.
- Start the first section immediately after its delimiter.
"""
    raw = _llm(prompt)
    if not raw:
        return {}
    return _parse_sections(raw)


def _parse_sections(raw: str) -> Dict[str, str]:
    result: Dict[str, str] = {}
    # Split on ###SECTION:key###
    parts = re.split(r"###SECTION:(\w+)###", raw)
    i = 1
    while i + 1 <= len(parts):
        key  = parts[i].strip()
        body = parts[i + 1].strip() if i + 1 < len(parts) else ""
        if key in AI_SECTIONS and body:
            result[key] = body
        i += 2
    return result


# ── Confidence rules ──────────────────────────────────────────────────────────

SECTION_CONFIDENCE: Dict[str, tuple] = {
    "company_background":   ("high",   "Extracted directly from structured company data"),
    "group_structure":      ("medium", "Inferred from available data; verify with MCA records"),
    "management_profile":   ("medium", "Based on available promoter data; KYC verification required"),
    "business_model":       ("medium", "Inferred from financials and research; verify key claims"),
    "industry_analysis":    ("medium", "Drawn from sector knowledge base and web research"),
    "financial_analysis":   ("high",   "Derived from computed financial ratios and extracted data"),
    "working_capital":      ("medium", "Inferred from balance sheet; verify against stock statement"),
    "banking_arrangement":  ("low",    "Template only — RM must obtain CIBIL, CMR, and existing facility details"),
    "proposed_structure":   ("medium", "DP calculation uses balance sheet data; update with fresh stock statement"),
    "peer_comparison":      ("medium", "Peer figures are approximate; verify against latest annual reports"),
    "key_issues":           ("medium", "Synthesised from ratios and research; RM judgement required"),
    "recommendation":       ("low",    "AI scaffold only — recommendation MUST be authored by RM"),
    "executive_summary":    ("medium", "Synthesised from all other sections; review each source section"),
}


def _resolve_confidence(section_key: str, financials: Dict) -> tuple:
    confidence, reason = SECTION_CONFIDENCE.get(section_key, ("medium", "AI-generated content"))
    if section_key == "company_background":
        ci = financials.get("company_info", {})
        if not ci.get("name") and not ci.get("description"):
            return ("medium", "Company info sparse — verify background details")
    return (confidence, reason)


# ── Public entry point ────────────────────────────────────────────────────────

def generate_cam_sections(
    financials: Dict,
    ratios: Dict,
    company_name: str,
    research_brief: str = "",
    regenerate: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate AI-drafted CAM sections.

    Args:
        financials: Extracted financial data
        ratios: Computed ratios
        company_name: Borrower name
        research_brief: Optional research brief text
        regenerate: If set, generate only this specific section key

    Returns:
        Dict with section keys → {"content": str, "user_edited": False, "ai_generated": True}
    """
    context_text = _build_context_text(financials, ratios, company_name, research_brief)

    if regenerate and regenerate in AI_SECTIONS:
        # Single section regeneration
        content = _draft_section(regenerate, context_text, company_name)
        conf, reason = _resolve_confidence(regenerate, financials)
        return {
            regenerate: {
                "content":           content,
                "user_edited":       False,
                "ai_generated":      True,
                "confidence":        conf,
                "confidence_reason": reason,
                "reviewed":          False,
                "low_verified":      False,
                "locked":            False,
            }
        }

    # Try batch generation first
    batch_sections = [k for k in AI_SECTIONS if k != "executive_summary"]
    logger.info(f"[CAM] Batch-generating {len(batch_sections)} sections for {company_name}")
    batch = _draft_all_sections_batch(context_text, company_name, batch_sections)

    sections: Dict[str, Any] = {}

    for key in batch_sections:
        content = batch.get(key, "")
        if not content:
            # Fallback: generate individually
            logger.info(f"[CAM] Batch missed section '{key}', generating individually")
            content = _draft_section(key, context_text, company_name)
        conf, reason = _resolve_confidence(key, financials)
        sections[key] = {
            "content":           content,
            "user_edited":       False,
            "ai_generated":      True,
            "confidence":        conf,
            "confidence_reason": reason,
            "reviewed":          False,
            "low_verified":      False,
            "locked":            False,
        }

    # Generate executive_summary last — it synthesises the other sections
    summary_snippets = []
    for key in ["company_background", "business_model", "financial_analysis", "key_issues", "recommendation"]:
        sec = sections.get(key, {})
        content = sec.get("content", "")
        if content:
            summary_snippets.append(f"[{key.upper()}]\n{content[:600]}")
    exec_context = context_text + (
        "\n\n--- SECTION SUMMARIES ---\n" + "\n\n".join(summary_snippets)
        if summary_snippets else ""
    )
    exec_content = _draft_section("executive_summary", exec_context, company_name)
    conf, reason = _resolve_confidence("executive_summary", financials)
    sections["executive_summary"] = {
        "content":           exec_content,
        "user_edited":       False,
        "ai_generated":      True,
        "confidence":        conf,
        "confidence_reason": reason,
        "reviewed":          False,
        "low_verified":      False,
        "locked":            False,
    }

    # Scaffold manual sections (empty, RM fills these)
    sections["banking_arrangement"] = {
        "arrangement_type": "sole",   # sole | multiple | consortium
        "banks": [],                  # [{name, limit_cr, outstanding_cr, type}]
        "remarks": "",
        "user_edited": False,
        "ai_generated": False,
    }
    sections["account_conduct"] = {
        "content": "",
        "user_edited": False,
        "ai_generated": False,
    }

    # Management PEP fields supplement
    if "management_profile" in sections:
        sections["management_profile"]["pep_checked"] = False
        sections["management_profile"]["pep_notes"]   = ""

    return sections
