"""
CAM Section Draft Generator.

Generates AI-drafted text sections for the structured Credit Appraisal Memorandum.
Each section is labelled and returned as a dict for the RM to review and edit.

Sections generated by AI:
  - company_background
  - group_structure
  - management_profile
  - business_model
  - industry_analysis
  - financial_analysis
  - working_capital
  - key_issues
  - recommendation
  - executive_summary   (generated last — synthesises all other sections)

Sections that are manual (RM-filled) — NOT generated:
  - banking_arrangement  (type, bank table)
  - account_conduct      (free text)
"""
import os
import re
import logging
import httpx
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

# ── Delimiter used to split sections ──────────────────────────────────────────
_DELIM = "###SECTION:"

AI_SECTIONS = [
    "company_background",
    "group_structure",
    "management_profile",
    "business_model",
    "industry_analysis",
    "financial_analysis",
    "working_capital",
    "key_issues",
    "recommendation",
    "executive_summary",   # generated last — synthesises all others
]

SECTION_PROMPTS = {
    "company_background": (
        "Write 2-3 paragraphs on the company's background: date of incorporation, "
        "registered office, nature of business, key business segments, "
        "milestones/major events. Use only facts from the data provided."
    ),
    "group_structure": (
        "Describe the group/corporate structure: parent company (if any), "
        "key subsidiaries and associates, cross-holdings, group turnover (if inferable). "
        "If no group data is available, state 'Standalone entity — no major subsidiaries identified'."
    ),
    "management_profile": (
        "Describe the promoter/management team: names and roles of key directors, "
        "promoter background, promoter holding percentage, any management changes. "
        "Comment on management quality signals from the research brief. "
        "Flag if any Politically Exposed Person (PEP) indicators are present."
    ),
    "business_model": (
        "Explain the company's business model: how it generates revenue, "
        "key customers/markets, supply chain, competitive positioning, "
        "key contracts or clients (if inferable). Reference the industry and "
        "company information provided."
    ),
    "industry_analysis": (
        "Analyse the industry context: sector growth trends, key demand drivers, "
        "competitive intensity, regulatory environment, raw material/input cost dynamics, "
        "and tailwinds/headwinds for the borrower's specific industry segment."
    ),
    "key_issues": (
        "Identify 4-6 key credit issues and risks specific to this borrower: "
        "financial risks (leverage, coverage), operational risks, industry risks, "
        "management/governance risks, and any specific red flags from the data. "
        "Format each as: **Issue N: [Title]** — [2-3 sentence explanation with evidence]."
    ),
    "recommendation": (
        "Write a credit recommendation: state whether to recommend approval/decline/further review, "
        "suggested loan amount (if applicable), key conditions precedent, "
        "financial covenants to impose, and monitoring requirements. "
        "Base the recommendation strictly on the financial and qualitative data provided."
    ),
    "financial_analysis": (
        "Write a financial analysis narrative covering: revenue and PAT trend over 3–5 years, "
        "EBITDA margin trajectory, debt levels and leverage trend, interest coverage and DSCR adequacy, "
        "working capital efficiency (debtor/inventory/creditor days), and overall credit quality assessment. "
        "Reference specific figures from the data. Flag any deteriorating trends or anomalies explicitly."
    ),
    "working_capital": (
        "Analyse the working capital position: describe the operating cycle length, "
        "key components (inventory days, debtor days, creditor days), adequacy of working capital limits, "
        "drawing power assessment based on current assets, and any concerns around WC utilisation patterns. "
        "Use only data available; flag areas requiring stock statement verification."
    ),
    "executive_summary": (
        "Write a concise executive summary (maximum 1 page) covering: borrower name and proposed facility, "
        "business overview in 2–3 sentences, key financial highlights (revenue, PAT, DSCR, leverage), "
        "credit strengths, top 2–3 risk factors, and the recommended credit decision. "
        "This is the first section a credit committee member will read — make it crisp and decisive."
    ),
}


# ── LLM helpers ───────────────────────────────────────────────────────────────

def _ollama_call(prompt: str) -> str:
    url   = os.getenv("OLLAMA_URL", "http://localhost:11434")
    model = os.getenv("OLLAMA_MODEL", "qwen3:8b")
    try:
        resp = httpx.post(
            f"{url}/v1/chat/completions",
            json={
                "model": model,
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are a senior credit risk analyst at an Indian commercial bank. "
                            "Write formal, concise, banker-grade credit appraisal sections. "
                            "Use ONLY the data provided. Do NOT fabricate figures. "
                            "Do NOT include any <think> tags or reasoning traces. "
                            "Output ONLY the requested section text in plain prose (no extra headings)."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
                "stream": False,
            },
            timeout=300.0,
        )
        resp.raise_for_status()
        text = resp.json()["choices"][0]["message"]["content"].strip()
        return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    except Exception as e:
        logger.error(f"Ollama call error: {e}")
        return ""


def _gemini_call(prompt: str) -> str:
    try:
        from google import genai
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            return ""
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="models/gemini-flash-lite-latest",
            contents=prompt,
        )
        return response.text.strip()
    except Exception as e:
        logger.error(f"Gemini call error: {e}")
        return ""


def _claude_call(prompt: str) -> str:
    """Call Claude via the `claude` CLI (uses Claude Code Pro subscription — no API key needed)."""
    import subprocess
    system = (
        "You are a senior credit risk analyst at an Indian commercial bank. "
        "Write formal, concise, banker-grade credit appraisal sections. "
        "Use ONLY the data provided. Do NOT fabricate figures. "
        "Output ONLY the requested section text in plain prose (no extra headings)."
    )
    full_prompt = f"{system}\n\n{prompt}"
    try:
        result = subprocess.run(
            ["claude", "-p", full_prompt],
            capture_output=True,
            text=True,
            timeout=300,
        )
        if result.returncode != 0:
            logger.error(f"Claude CLI error: {result.stderr}")
            return ""
        return result.stdout.strip()
    except Exception as e:
        logger.error(f"Claude CLI call error: {e}")
        return ""


def _llm(prompt: str) -> str:
    provider = os.getenv("MEMO_PROVIDER", "gemini").lower()
    if provider == "claude":
        result = _claude_call(prompt)
        if result:
            return result
        logger.warning("Claude CLI unavailable, falling back to Gemini")
        result = _gemini_call(prompt)
        if result:
            return result
    elif provider == "gemini":
        result = _gemini_call(prompt)
        if result:
            return result
        logger.warning("Gemini failed, falling back to Ollama")
    result = _ollama_call(prompt)
    if result:
        return result
    logger.warning("Ollama failed, falling back to Gemini")
    return _gemini_call(prompt)


# ── Context builder ───────────────────────────────────────────────────────────

def _build_context_text(financials: Dict, ratios: Dict, company_name: str, research_brief: str) -> str:
    lines = [f"COMPANY: {company_name}"]

    ci = financials.get("company_info", {})
    if ci.get("industry"):
        lines.append(f"INDUSTRY: {ci['industry']}")
    if ci.get("description"):
        lines.append(f"DESCRIPTION: {ci['description']}")

    # P&L multi-year if available (Screener format)
    pl = financials.get("profit_loss", {})
    years  = pl.get("years",   [])
    rev    = pl.get("revenue", [])
    pat    = pl.get("pat",     [])
    ebitda = pl.get("ebitda",  [])
    if years:
        lines.append("\nFINANCIALS (₹ Cr):")
        for i, yr in enumerate(years):
            r = rev[i]   if i < len(rev)    else None
            p = pat[i]   if i < len(pat)    else None
            e = ebitda[i] if i < len(ebitda) else None
            lines.append(
                f"  {yr}: Revenue={r}, PAT={p}, EBITDA={e}"
            )
    else:
        # Single-year from structured financials
        rev_c = pl.get("revenue", {})
        if isinstance(rev_c, dict):
            lines.append(f"\nREVENUE: {rev_c.get('revenue_from_operations') or rev_c.get('total_income')}")

    bs = financials.get("balance_sheet", {})
    borrow = bs.get("borrowings", [])
    if borrow:
        lines.append(f"BORROWINGS: {borrow}")
    networth = bs.get("equity", {})
    if isinstance(networth, dict):
        eq = networth.get("total_equity")
        if eq:
            lines.append(f"NET WORTH: ₹{eq} Cr")

    key_ratios = {
        "Debt/Equity": ratios.get("debt_equity"),
        "Current Ratio": ratios.get("current_ratio"),
        "Interest Coverage": ratios.get("interest_coverage"),
        "DSCR": ratios.get("dscr"),
        "EBITDA Margin %": ratios.get("ebitda_margin"),
        "ROCE %": ratios.get("roce"),
    }
    kr_lines = [f"  {k}: {v}" for k, v in key_ratios.items() if v is not None]
    if kr_lines:
        lines.append("\nKEY RATIOS:\n" + "\n".join(kr_lines))

    screener = financials.get("screener", {})
    prom = screener.get("promoter_holding") or financials.get("promoter_holding")
    if prom:
        lines.append(f"PROMOTER HOLDING: {prom}%")

    peers = financials.get("peers", [])
    if peers:
        lines.append(f"\nPEERS: {', '.join(str(p.get('name', p)) for p in peers[:5])}")

    if research_brief:
        lines.append(f"\nWEB RESEARCH BRIEF:\n{research_brief[:3000]}")

    return "\n".join(lines)


# ── Per-section generation ────────────────────────────────────────────────────

def _draft_section(
    section_key: str,
    context_text: str,
    company_name: str,
    extra_brief: str = "",
) -> str:
    instruction = SECTION_PROMPTS.get(section_key, "Write a brief analysis for this section.")
    prompt = f"""{context_text}

{'---\nADDITIONAL CONTEXT:\n' + extra_brief if extra_brief else ''}

---
TASK: For borrower "{company_name}", write the **{section_key.replace('_', ' ').title()}** section of the Credit Appraisal Memorandum.

{instruction}

Write in formal banker prose. 2-4 paragraphs unless the instruction says otherwise.
Output ONLY the section content — no headings, no preamble."""
    return _llm(prompt)


# ── Batch generation via a single LLM call ───────────────────────────────────

def _draft_all_sections_batch(
    context_text: str,
    company_name: str,
    sections: list = None,
) -> Dict[str, str]:
    """
    One LLM call to generate all AI sections separated by delimiters.
    Fallback: generate each section individually.
    """
    target = sections if sections is not None else AI_SECTIONS
    section_list = "\n".join(
        f"{_DELIM}{k}###\n{SECTION_PROMPTS[k]}"
        for k in target if k in SECTION_PROMPTS
    )
    prompt = f"""{context_text}

---
You are writing a Credit Appraisal Memorandum for "{company_name}".
Generate ALL sections below. Each section must start with its delimiter exactly as shown.

{section_list}

RULES:
- Use ONLY the data provided above. Do NOT fabricate any figures.
- Each section: 2-4 paragraphs of formal banker prose.
- Do NOT add extra headings inside sections.
- Do NOT output any <think> tags.
- Start the first section immediately after its delimiter.
"""
    raw = _llm(prompt)
    if not raw:
        return {}
    return _parse_sections(raw)


def _parse_sections(raw: str) -> Dict[str, str]:
    result: Dict[str, str] = {}
    # Split on ###SECTION:key###
    parts = re.split(r"###SECTION:(\w+)###", raw)
    i = 1
    while i + 1 <= len(parts):
        key  = parts[i].strip()
        body = parts[i + 1].strip() if i + 1 < len(parts) else ""
        if key in AI_SECTIONS and body:
            result[key] = body
        i += 2
    return result


# ── Confidence rules ──────────────────────────────────────────────────────────

SECTION_CONFIDENCE: Dict[str, tuple] = {
    "company_background":  ("high",   "Extracted directly from structured company data"),
    "group_structure":     ("medium", "Inferred from available data; verify with MCA records"),
    "management_profile":  ("medium", "Based on available promoter data; KYC verification required"),
    "business_model":      ("medium", "Inferred from financials and research; verify key claims"),
    "industry_analysis":   ("medium", "Drawn from sector knowledge base and web research"),
    "financial_analysis":  ("high",   "Derived from computed financial ratios and extracted data"),
    "working_capital":     ("medium", "Inferred from balance sheet; verify against stock statement"),
    "key_issues":          ("medium", "Synthesised from ratios and research; RM judgement required"),
    "recommendation":      ("low",    "AI scaffold only — recommendation MUST be authored by RM"),
    "executive_summary":   ("medium", "Synthesised from all other sections; review each source section"),
}


def _resolve_confidence(section_key: str, financials: Dict) -> tuple:
    confidence, reason = SECTION_CONFIDENCE.get(section_key, ("medium", "AI-generated content"))
    if section_key == "company_background":
        ci = financials.get("company_info", {})
        if not ci.get("name") and not ci.get("description"):
            return ("medium", "Company info sparse — verify background details")
    return (confidence, reason)


# ── Public entry point ────────────────────────────────────────────────────────

def generate_cam_sections(
    financials: Dict,
    ratios: Dict,
    company_name: str,
    research_brief: str = "",
    regenerate: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate AI-drafted CAM sections.

    Args:
        financials: Extracted financial data
        ratios: Computed ratios
        company_name: Borrower name
        research_brief: Optional research brief text
        regenerate: If set, generate only this specific section key

    Returns:
        Dict with section keys → {"content": str, "user_edited": False, "ai_generated": True}
    """
    context_text = _build_context_text(financials, ratios, company_name, research_brief)

    if regenerate and regenerate in AI_SECTIONS:
        # Single section regeneration
        content = _draft_section(regenerate, context_text, company_name)
        conf, reason = _resolve_confidence(regenerate, financials)
        return {
            regenerate: {
                "content":           content,
                "user_edited":       False,
                "ai_generated":      True,
                "confidence":        conf,
                "confidence_reason": reason,
                "reviewed":          False,
                "low_verified":      False,
                "locked":            False,
            }
        }

    # Try batch generation first
    batch_sections = [k for k in AI_SECTIONS if k != "executive_summary"]
    logger.info(f"[CAM] Batch-generating {len(batch_sections)} sections for {company_name}")
    batch = _draft_all_sections_batch(context_text, company_name, batch_sections)

    sections: Dict[str, Any] = {}

    for key in batch_sections:
        content = batch.get(key, "")
        if not content:
            # Fallback: generate individually
            logger.info(f"[CAM] Batch missed section '{key}', generating individually")
            content = _draft_section(key, context_text, company_name)
        conf, reason = _resolve_confidence(key, financials)
        sections[key] = {
            "content":           content,
            "user_edited":       False,
            "ai_generated":      True,
            "confidence":        conf,
            "confidence_reason": reason,
            "reviewed":          False,
            "low_verified":      False,
            "locked":            False,
        }

    # Generate executive_summary last — it synthesises the other sections
    summary_snippets = []
    for key in ["company_background", "business_model", "financial_analysis", "key_issues", "recommendation"]:
        sec = sections.get(key, {})
        content = sec.get("content", "")
        if content:
            summary_snippets.append(f"[{key.upper()}]\n{content[:600]}")
    exec_context = context_text + (
        "\n\n--- SECTION SUMMARIES ---\n" + "\n\n".join(summary_snippets)
        if summary_snippets else ""
    )
    exec_content = _draft_section("executive_summary", exec_context, company_name)
    conf, reason = _resolve_confidence("executive_summary", financials)
    sections["executive_summary"] = {
        "content":           exec_content,
        "user_edited":       False,
        "ai_generated":      True,
        "confidence":        conf,
        "confidence_reason": reason,
        "reviewed":          False,
        "low_verified":      False,
        "locked":            False,
    }

    # Scaffold manual sections (empty, RM fills these)
    sections["banking_arrangement"] = {
        "arrangement_type": "sole",   # sole | multiple | consortium
        "banks": [],                  # [{name, limit_cr, outstanding_cr, type}]
        "remarks": "",
        "user_edited": False,
        "ai_generated": False,
    }
    sections["account_conduct"] = {
        "content": "",
        "user_edited": False,
        "ai_generated": False,
    }

    # Management PEP fields supplement
    if "management_profile" in sections:
        sections["management_profile"]["pep_checked"] = False
        sections["management_profile"]["pep_notes"]   = ""

    return sections
