"""
CAM Section Draft Generator.

Generates AI-drafted text sections for the structured Credit Appraisal Memorandum.
Each section is labelled and returned as a dict for the RM to review and edit.

Sections generated by AI:
  - company_background
  - group_structure
  - management_profile
  - business_model
  - industry_analysis
  - financial_analysis
  - working_capital
  - key_issues
  - recommendation
  - executive_summary   (generated last — synthesises all other sections)

Sections that are manual (RM-filled) — NOT generated:
  - banking_arrangement  (type, bank table)
  - account_conduct      (free text)
"""
import os
import re
import logging
import httpx
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

# ── Delimiter used to split sections ──────────────────────────────────────────
_DELIM = "###SECTION:"

AI_SECTIONS = [
    "company_background",
    "group_structure",
    "management_profile",
    "business_model",
    "industry_analysis",
    "financial_analysis",
    "working_capital",
    "banking_arrangement",
    "proposed_structure",
    "peer_comparison",
    "key_issues",
    "recommendation",
    "executive_summary",   # generated last — synthesises all others
]

SECTION_PROMPTS = {
    "company_background": (
        "Write 2-3 paragraphs on the company's background: date of incorporation, "
        "registered office, nature of business, key business segments, "
        "milestones/major events. Use only facts from the data provided."
    ),
    "group_structure": (
        "Describe the group/corporate structure: parent company (if any), "
        "key subsidiaries and associates, cross-holdings, group turnover (if inferable). "
        "If no group data is available, state 'Standalone entity — no major subsidiaries identified'."
    ),
    "management_profile": (
        "Describe the promoter/management team: names and roles of key directors, "
        "promoter background, promoter holding percentage, any management changes. "
        "Comment on management quality signals from the research brief. "
        "Flag if any Politically Exposed Person (PEP) indicators are present."
    ),
    "business_model": (
        "Explain the company's business model: how it generates revenue, "
        "key customers/markets, supply chain, competitive positioning, "
        "key contracts or clients (if inferable). Reference the industry and "
        "company information provided."
    ),
    "industry_analysis": (
        "Analyse the industry context: sector growth trends, key demand drivers, "
        "competitive intensity, regulatory environment, raw material/input cost dynamics, "
        "and tailwinds/headwinds for the borrower's specific industry segment."
    ),
    "key_issues": (
        "Identify 4-6 key credit issues and risks specific to this borrower: "
        "financial risks (leverage, coverage), operational risks, industry risks, "
        "management/governance risks, and any specific red flags from the data. "
        "Format each as: **Issue N: [Title]** — [2-3 sentence explanation with evidence]."
    ),
    "recommendation": (
        "Write a credit recommendation: state whether to recommend approval/decline/further review, "
        "suggested loan amount (if applicable), key conditions precedent, "
        "financial covenants to impose, and monitoring requirements. "
        "Base the recommendation strictly on the financial and qualitative data provided."
    ),
    "financial_analysis": (
        "Write a financial analysis narrative covering: revenue and PAT trend over 3–5 years, "
        "EBITDA margin trajectory, debt levels and leverage trend, interest coverage and DSCR adequacy, "
        "working capital efficiency (debtor/inventory/creditor days), and overall credit quality assessment. "
        "Reference specific figures from the data. Flag any deteriorating trends or anomalies explicitly."
    ),
    "working_capital": (
        "Analyse the working capital position: describe the operating cycle length, "
        "key components (inventory days, debtor days, creditor days), adequacy of working capital limits, "
        "drawing power assessment based on current assets, and any concerns around WC utilisation patterns. "
        "Use only data available; flag areas requiring stock statement verification."
    ),
    "executive_summary": (
        "Write a concise executive summary (maximum 1 page) covering: borrower name and proposed facility, "
        "business overview in 2–3 sentences, key financial highlights (revenue, PAT, DSCR, leverage), "
        "credit strengths, top 2–3 risk factors, and the recommended credit decision. "
        "This is the first section a credit committee member will read — make it crisp and decisive."
    ),
    "banking_arrangement": (
        "Generate a structured Banking Arrangement section for a Credit Appraisal Memorandum. "
        "Include:\n"
        "1. A markdown table of the borrower's existing credit facilities with ALL banks, with columns: "
        "Bank Name | Facility Type | Sanctioned Limit (₹ Cr) | Outstanding (₹ Cr) | Security | Remarks. "
        "If specific details are not available in the data, use '[To be obtained]' as placeholder — DO NOT fabricate figures.\n"
        "2. Account conduct summary: any instances of irregularity, bounced instruments, overutilisation.\n"
        "3. CIBIL/CMR score and status (use '[To be verified]' if not available).\n"
        "4. Total banking system exposure (sum across all lenders).\n"
        "5. One paragraph on the proposed bank's relationship with the borrower if any.\n"
        "Use a professional formal tone. Flag clearly what information is pending."
    ),
    "proposed_structure": (
        "Generate the Proposed Credit Facility Structure section. Include:\n"
        "1. Facility details: Type (Working Capital — Cash Credit/Overdraft), Amount (₹ Cr), Tenor, "
        "Purpose, Disbursement mode.\n"
        "2. Drawing Power (DP) Calculation using Indian banking norms (Tandon Committee Method II):\n"
        "   Present a markdown table:\n"
        "   | Item | Amount (₹ Cr) |\n"
        "   | Inventory (at cost) | [value or 'As per stock statement'] |\n"
        "   | Trade Receivables (< 90 days) | [value or 'As per debtor ageing'] |\n"
        "   | Other Current Assets | [value] |\n"
        "   | **Total Current Assets (A)** | [total] |\n"
        "   | Less: Trade Creditors | [value] |\n"
        "   | Less: Other Current Liabilities | [value] |\n"
        "   | **Total Current Liabilities excl. Bank Borrowings (B)** | [total] |\n"
        "   | **Working Capital Gap (A-B)** | [gap] |\n"
        "   | Bank Financing (75% of WCG — Method II) | [75% of gap] |\n"
        "   | **Drawing Power (min of Bank Financing & Limit)** | [DP] |\n"
        "   Use actual balance sheet figures where available. Flag '[Requires stock statement]' where live data is needed.\n"
        "3. Security structure:\n"
        "   - Primary: Hypothecation of entire current assets (stock, book debts) — first charge\n"
        "   - Collateral: [as applicable]\n"
        "   - Guarantee: Corporate/personal guarantee if applicable\n"
        "4. Pricing: Interest rate (Base Rate / MCLR + spread), processing fee, review frequency.\n"
        "5. Repayment: For WC — annual review; for term — EMI schedule.\n"
        "Use actual financial data from the context where available."
    ),
    "peer_comparison": (
        "Write a Peer Comparison section with:\n"
        "1. A markdown table comparing the borrower against 3-4 named peer companies on these metrics:\n"
        "   Company | Revenue (₹ Cr) | EBITDA Margin % | PAT Margin % | D/E Ratio | Interest Coverage | ROCE % | Credit Rating\n"
        "   Use the peer list and financial data provided. If peer financials are not in the data, "
        "   use approximate publicly known figures with a note '(approximate)'.\n"
        "2. A 2-3 sentence narrative on how the borrower compares to peers — strengths and gaps.\n"
        "3. Industry median benchmarks for the sector where available.\n"
        "Base this on the sector and peers provided in the context."
    ),
}


# ── LLM helpers ───────────────────────────────────────────────────────────────

def _ollama_call(prompt: str) -> str:
    url   = os.getenv("OLLAMA_URL", "http://localhost:11434")
    model = os.getenv("OLLAMA_MODEL", "qwen3:8b")
    try:
        resp = httpx.post(
            f"{url}/v1/chat/completions",
            json={
                "model": model,
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are a senior credit risk analyst at an Indian commercial bank. "
                            "Write formal, concise, banker-grade credit appraisal sections. "
                            "Use ONLY the data provided. Do NOT fabricate figures. "
                            "Do NOT include any <think> tags or reasoning traces. "
                            "Output ONLY the requested section text in plain prose (no extra headings)."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
                "stream": False,
            },
            timeout=300.0,
        )
        resp.raise_for_status()
        text = resp.json()["choices"][0]["message"]["content"].strip()
        return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    except Exception as e:
        logger.error(f"Ollama call error: {e}")
        return ""


def _gemini_call(prompt: str) -> str:
    try:
        from google import genai
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            return ""
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="models/gemini-flash-lite-latest",
            contents=prompt,
        )
        return response.text.strip()
    except Exception as e:
        logger.error(f"Gemini call error: {e}")
        return ""


def _claude_call(prompt: str) -> str:
    """Call Claude via the `claude` CLI (uses Claude Code Pro subscription — no API key needed)."""
    import subprocess
    system = (
        "You are a senior credit risk analyst at an Indian commercial bank. "
        "Write formal, concise, banker-grade credit appraisal sections. "
        "Use ONLY the data provided. Do NOT fabricate figures. "
        "Output ONLY the requested section text in plain prose (no extra headings)."
    )
    full_prompt = f"{system}\n\n{prompt}"
    try:
        result = subprocess.run(
            ["claude", "-p", full_prompt],
            capture_output=True,
            text=True,
            timeout=300,
        )
        if result.returncode != 0:
            logger.error(f"Claude CLI error: {result.stderr}")
            return ""
        return result.stdout.strip()
    except Exception as e:
        logger.error(f"Claude CLI call error: {e}")
        return ""


def _llm(prompt: str) -> str:
    provider = os.getenv("MEMO_PROVIDER", "gemini").lower()
    if provider == "claude":
        result = _claude_call(prompt)
        if result:
            return result
        logger.warning("Claude CLI unavailable, falling back to Gemini")
        result = _gemini_call(prompt)
        if result:
            return result
    elif provider == "gemini":
        result = _gemini_call(prompt)
        if result:
            return result
        logger.warning("Gemini failed, falling back to Ollama")
    result = _ollama_call(prompt)
    if result:
        return result
    logger.warning("Ollama failed, falling back to Gemini")
    return _gemini_call(prompt)


# ── Context builder ───────────────────────────────────────────────────────────

def _fmt(v, decimals=2):
    """Format a number or return 'N/A'."""
    if v is None:
        return "N/A"
    try:
        return f"{float(v):,.{decimals}f}"
    except (TypeError, ValueError):
        return str(v)


def _build_context_text(financials: Dict, ratios: Dict, company_name: str, research_brief: str) -> str:
    lines = [f"COMPANY: {company_name}"]

    ci = financials.get("company_info", {})
    if ci.get("industry"):
        lines.append(f"INDUSTRY: {ci['industry']}")
    if ci.get("about") or ci.get("description"):
        lines.append(f"ABOUT: {(ci.get('about') or ci.get('description', ''))[:400]}")
    if ci.get("key_points"):
        lines.append("KEY POINTS: " + " | ".join(str(x) for x in ci["key_points"][:6]))

    pl = financials.get("profit_loss", {})
    bs = financials.get("balance_sheet", {})
    cf = financials.get("cash_flow", {})

    years  = pl.get("years", [])
    rev    = pl.get("revenue", [])
    pat    = pl.get("pat", [])
    ebitda = pl.get("ebitda", [])
    pbt    = pl.get("pbt", [])
    interest = pl.get("interest", []) or pl.get("finance_costs", [])
    dep    = pl.get("depreciation", [])

    bs_years = bs.get("years", years)
    borrowings = bs.get("borrowings", [])
    total_equity = bs.get("total_equity", [])
    total_assets = bs.get("total_assets", [])

    # Normalise to lists
    def _to_list(x):
        return x if isinstance(x, list) else []

    rev = _to_list(rev); pat = _to_list(pat); ebitda = _to_list(ebitda)
    pbt = _to_list(pbt); interest = _to_list(interest); dep = _to_list(dep)
    borrowings = _to_list(borrowings); total_equity = _to_list(total_equity)
    total_assets = _to_list(total_assets)

    if years:
        # ── Multi-year financial table ────────────────────────────────────────
        col_w = 14
        header = "Metric".ljust(28) + "".join(str(y).rjust(col_w) for y in years)
        sep = "-" * (28 + col_w * len(years))
        table_rows = ["\nFINANCIALS (₹ Crore):", sep, header, sep]

        def row(label, arr):
            return label.ljust(28) + "".join(_fmt(arr[i] if i < len(arr) else None).rjust(col_w) for i in range(len(years)))

        table_rows.append(row("Revenue from Operations", rev))
        table_rows.append(row("EBITDA", ebitda))

        # EBITDA margin %
        ebitda_margins = []
        for i in range(len(years)):
            r_v = rev[i] if i < len(rev) else None
            e_v = ebitda[i] if i < len(ebitda) else None
            m = round(e_v / r_v * 100, 1) if r_v and e_v and r_v > 0 else None
            ebitda_margins.append(m)
        table_rows.append(row("EBITDA Margin %", ebitda_margins))
        table_rows.append(row("Profit Before Tax", pbt))
        table_rows.append(row("Profit After Tax (PAT)", pat))

        # PAT margin %
        pat_margins = []
        for i in range(len(years)):
            r_v = rev[i] if i < len(rev) else None
            p_v = pat[i] if i < len(pat) else None
            m = round(p_v / r_v * 100, 1) if r_v and p_v and r_v > 0 else None
            pat_margins.append(m)
        table_rows.append(row("PAT Margin %", pat_margins))
        table_rows.append(row("Finance Costs", interest))
        table_rows.append(row("Depreciation", dep))
        table_rows.append(sep)
        table_rows.append(row("Total Assets", total_assets))
        table_rows.append(row("Total Borrowings", borrowings))
        table_rows.append(row("Total Equity / Net Worth", total_equity))

        # D/E ratio
        de_ratios = []
        for i in range(len(years)):
            b = borrowings[i] if i < len(borrowings) else None
            e = total_equity[i] if i < len(total_equity) else None
            de_ratios.append(round(b / e, 2) if b is not None and e and e > 0 else None)
        table_rows.append(row("Debt / Equity Ratio", de_ratios))

        # Interest coverage
        icr_series = []
        for i in range(len(years)):
            eb = ebitda[i] if i < len(ebitda) else None
            fi = interest[i] if i < len(interest) else None
            icr_series.append(round(eb / fi, 2) if eb and fi and fi > 0 else None)
        table_rows.append(row("Interest Coverage (x)", icr_series))

        table_rows.append(sep)
        lines.extend(table_rows)

        # CAGR summary
        if len(years) >= 2:
            n = len(years) - 1
            if rev and rev[0] and rev[-1] and rev[0] > 0:
                cagr = round(((rev[-1] / rev[0]) ** (1 / n) - 1) * 100, 1)
                lines.append(f"Revenue CAGR ({n}yr): {cagr}%")
            if pat and pat[0] and pat[-1] and pat[0] > 0 and pat[-1] > 0:
                cagr = round(((pat[-1] / pat[0]) ** (1 / n) - 1) * 100, 1)
                lines.append(f"PAT CAGR ({n}yr): {cagr}%")

        # Cash flow summary
        cfo_years = cf.get("years", [])
        cfo_vals = cf.get("operating", [])
        if cfo_years and cfo_vals:
            lines.append("Operating Cash Flow (₹ Cr): " +
                         ", ".join(f"{y}: {_fmt(v)}" for y, v in zip(cfo_years, cfo_vals)))

    else:
        # Single-year fallback
        rev_d = pl.get("revenue", {})
        if isinstance(rev_d, dict):
            rv = rev_d.get("revenue_from_operations") or rev_d.get("total_income")
            lines.append(f"\nREVENUE: ₹{_fmt(rv)} Cr")
        pm = pl.get("profit_metrics", {})
        if isinstance(pm, dict):
            lines.append(f"PAT: ₹{_fmt(pm.get('profit_after_tax'))} Cr | EBITDA: ₹{_fmt(pm.get('ebitda'))} Cr")

        eq = bs.get("equity", {})
        if isinstance(eq, dict) and eq.get("total_equity"):
            lines.append(f"NET WORTH: ₹{_fmt(eq['total_equity'])} Cr")

    # Screener ratios if available
    screener_ratios = financials.get("key_ratios_from_screener", {})
    if screener_ratios:
        lines.append("\nKEY RATIOS (Screener):")
        for k, v in screener_ratios.items():
            if v is not None and not isinstance(v, list):
                lines.append(f"  {k}: {v}")

    # Computed ratios
    key_ratios = {
        "Debt/Equity": ratios.get("debt_equity"),
        "Current Ratio": ratios.get("current_ratio"),
        "Interest Coverage (x)": ratios.get("interest_coverage"),
        "DSCR": ratios.get("dscr"),
        "EBITDA Margin %": ratios.get("ebitda_margin"),
        "ROCE %": ratios.get("roce"),
        "Debtor Days": screener_ratios.get("debtor_days") or ratios.get("debtor_days"),
        "Inventory Days": screener_ratios.get("inventory_days") or ratios.get("inventory_days"),
        "Creditor Days": screener_ratios.get("payable_days") or ratios.get("payable_days"),
    }
    kr_lines = [f"  {k}: {v}" for k, v in key_ratios.items() if v is not None]
    if kr_lines:
        lines.append("\nCOMPUTED RATIOS:\n" + "\n".join(kr_lines))

    # Shareholding
    sh = financials.get("shareholding", {})
    prom = sh.get("promoter_holding_pct") or financials.get("company_info", {}).get("promoter_holding")
    if prom:
        lines.append(f"\nPROMOTER HOLDING: {prom}%")
        trend = sh.get("promoter_trend", [])
        if trend:
            lines.append("Promoter trend: " + ", ".join(f"{t['period']}: {t['pct']}%" for t in trend[-4:]))

    # Peers
    peers = financials.get("peers", [])
    if peers:
        lines.append(f"\nPEER COMPANIES: {', '.join(str(p.get('Name', p.get('name', str(p)))) for p in peers[:5])}")

    # Credit ratings
    ratings = financials.get("company_info", {}).get("credit_ratings", [])
    if ratings:
        lines.append("\nCREDIT RATINGS: " + " | ".join(str(r) for r in ratings[:3]))

    if research_brief:
        lines.append(f"\nWEB RESEARCH BRIEF:\n{research_brief[:4000]}")

    return "\n".join(lines)


# ── Per-section generation ────────────────────────────────────────────────────

def _draft_section(
    section_key: str,
    context_text: str,
    company_name: str,
    extra_brief: str = "",
) -> str:
    instruction = SECTION_PROMPTS.get(section_key, "Write a brief analysis for this section.")
    prompt = f"""{context_text}

{'---\nADDITIONAL CONTEXT:\n' + extra_brief if extra_brief else ''}

---
TASK: For borrower "{company_name}", write the **{section_key.replace('_', ' ').title()}** section of the Credit Appraisal Memorandum.

{instruction}

Write in formal banker prose. 2-4 paragraphs unless the instruction says otherwise.
Output ONLY the section content — no headings, no preamble."""
    return _llm(prompt)


# ── Batch generation via a single LLM call ───────────────────────────────────

def _draft_all_sections_batch(
    context_text: str,
    company_name: str,
    sections: list = None,
) -> Dict[str, str]:
    """
    One LLM call to generate all AI sections separated by delimiters.
    Fallback: generate each section individually.
    """
    target = sections if sections is not None else AI_SECTIONS
    section_list = "\n".join(
        f"{_DELIM}{k}###\n{SECTION_PROMPTS[k]}"
        for k in target if k in SECTION_PROMPTS
    )
    prompt = f"""{context_text}

---
You are writing a Credit Appraisal Memorandum for "{company_name}".
Generate ALL sections below. Each section must start with its delimiter exactly as shown.

{section_list}

RULES:
- Use ONLY the data provided above. Do NOT fabricate any figures.
- Each section: 2-4 paragraphs of formal banker prose.
- Do NOT add extra headings inside sections.
- Do NOT output any <think> tags.
- Start the first section immediately after its delimiter.
"""
    raw = _llm(prompt)
    if not raw:
        return {}
    return _parse_sections(raw)


def _parse_sections(raw: str) -> Dict[str, str]:
    result: Dict[str, str] = {}
    # Split on ###SECTION:key###
    parts = re.split(r"###SECTION:(\w+)###", raw)
    i = 1
    while i + 1 <= len(parts):
        key  = parts[i].strip()
        body = parts[i + 1].strip() if i + 1 < len(parts) else ""
        if key in AI_SECTIONS and body:
            result[key] = body
        i += 2
    return result


# ── Confidence rules ──────────────────────────────────────────────────────────

SECTION_CONFIDENCE: Dict[str, tuple] = {
    "company_background":   ("high",   "Extracted directly from structured company data"),
    "group_structure":      ("medium", "Inferred from available data; verify with MCA records"),
    "management_profile":   ("medium", "Based on available promoter data; KYC verification required"),
    "business_model":       ("medium", "Inferred from financials and research; verify key claims"),
    "industry_analysis":    ("medium", "Drawn from sector knowledge base and web research"),
    "financial_analysis":   ("high",   "Derived from computed financial ratios and extracted data"),
    "working_capital":      ("medium", "Inferred from balance sheet; verify against stock statement"),
    "banking_arrangement":  ("low",    "Template only — RM must obtain CIBIL, CMR, and existing facility details"),
    "proposed_structure":   ("medium", "DP calculation uses balance sheet data; update with fresh stock statement"),
    "peer_comparison":      ("medium", "Peer figures are approximate; verify against latest annual reports"),
    "key_issues":           ("medium", "Synthesised from ratios and research; RM judgement required"),
    "recommendation":       ("low",    "AI scaffold only — recommendation MUST be authored by RM"),
    "executive_summary":    ("medium", "Synthesised from all other sections; review each source section"),
}


def _resolve_confidence(section_key: str, financials: Dict) -> tuple:
    confidence, reason = SECTION_CONFIDENCE.get(section_key, ("medium", "AI-generated content"))
    if section_key == "company_background":
        ci = financials.get("company_info", {})
        if not ci.get("name") and not ci.get("description"):
            return ("medium", "Company info sparse — verify background details")
    return (confidence, reason)


# ── Public entry point ────────────────────────────────────────────────────────

def generate_cam_sections(
    financials: Dict,
    ratios: Dict,
    company_name: str,
    research_brief: str = "",
    regenerate: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate AI-drafted CAM sections.

    Args:
        financials: Extracted financial data
        ratios: Computed ratios
        company_name: Borrower name
        research_brief: Optional research brief text
        regenerate: If set, generate only this specific section key

    Returns:
        Dict with section keys → {"content": str, "user_edited": False, "ai_generated": True}
    """
    context_text = _build_context_text(financials, ratios, company_name, research_brief)

    if regenerate and regenerate in AI_SECTIONS:
        # Single section regeneration
        content = _draft_section(regenerate, context_text, company_name)
        conf, reason = _resolve_confidence(regenerate, financials)
        return {
            regenerate: {
                "content":           content,
                "user_edited":       False,
                "ai_generated":      True,
                "confidence":        conf,
                "confidence_reason": reason,
                "reviewed":          False,
                "low_verified":      False,
                "locked":            False,
            }
        }

    # Try batch generation first
    batch_sections = [k for k in AI_SECTIONS if k != "executive_summary"]
    logger.info(f"[CAM] Batch-generating {len(batch_sections)} sections for {company_name}")
    batch = _draft_all_sections_batch(context_text, company_name, batch_sections)

    sections: Dict[str, Any] = {}

    for key in batch_sections:
        content = batch.get(key, "")
        if not content:
            # Fallback: generate individually
            logger.info(f"[CAM] Batch missed section '{key}', generating individually")
            content = _draft_section(key, context_text, company_name)
        conf, reason = _resolve_confidence(key, financials)
        sections[key] = {
            "content":           content,
            "user_edited":       False,
            "ai_generated":      True,
            "confidence":        conf,
            "confidence_reason": reason,
            "reviewed":          False,
            "low_verified":      False,
            "locked":            False,
        }

    # Generate executive_summary last — it synthesises the other sections
    summary_snippets = []
    for key in ["company_background", "business_model", "financial_analysis", "key_issues", "recommendation"]:
        sec = sections.get(key, {})
        content = sec.get("content", "")
        if content:
            summary_snippets.append(f"[{key.upper()}]\n{content[:600]}")
    exec_context = context_text + (
        "\n\n--- SECTION SUMMARIES ---\n" + "\n\n".join(summary_snippets)
        if summary_snippets else ""
    )
    exec_content = _draft_section("executive_summary", exec_context, company_name)
    conf, reason = _resolve_confidence("executive_summary", financials)
    sections["executive_summary"] = {
        "content":           exec_content,
        "user_edited":       False,
        "ai_generated":      True,
        "confidence":        conf,
        "confidence_reason": reason,
        "reviewed":          False,
        "low_verified":      False,
        "locked":            False,
    }

    # Scaffold manual sections (empty, RM fills these)
    sections["banking_arrangement"] = {
        "arrangement_type": "sole",   # sole | multiple | consortium
        "banks": [],                  # [{name, limit_cr, outstanding_cr, type}]
        "remarks": "",
        "user_edited": False,
        "ai_generated": False,
    }
    sections["account_conduct"] = {
        "content": "",
        "user_edited": False,
        "ai_generated": False,
    }

    # Management PEP fields supplement
    if "management_profile" in sections:
        sections["management_profile"]["pep_checked"] = False
        sections["management_profile"]["pep_notes"]   = ""

    return sections
