/**
 * Data Room API hooks — hand-written (not generated by orval).
 * Follows the same pattern as generated/api.ts.
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "./custom-fetch";

// ── Types ─────────────────────────────────────────────────────────────────

export interface CaseDocument {
  id: number;
  case_id: number;
  doc_type: string;
  filename: string;
  storage_path: string;
  fiscal_year: string | null;
  extracted_data: Record<string, unknown> | null;
  source: string | null;
  created_at: string;
}

export interface DataRoomState {
  documents: CaseDocument[];
  extractedData: {
    financials?: Record<string, unknown>;
    research?: unknown[];
    peers?: unknown[];
    organogram?: Record<string, unknown>;
    security?: unknown[];
  } | null;
  completeness: number;
}

export interface Peer {
  symbol?: string;
  name: string;
  confirmed: boolean;
  suggested?: boolean;
  screenerData?: Record<string, unknown>;
}

// ── Query keys ────────────────────────────────────────────────────────────

export const getDataRoomQueryKey = (caseId: number) => ["dataRoom", caseId] as const;
export const getPeersQueryKey = (caseId: number) => ["dataRoomPeers", caseId] as const;

// ── GET data-room state ───────────────────────────────────────────────────

export const useGetDataRoom = (caseId: number) =>
  useQuery({
    queryKey: getDataRoomQueryKey(caseId),
    queryFn: () => customFetch<DataRoomState>(`/api/cases/${caseId}/data-room`),
    enabled: !!caseId,
  });

// ── POST fetch-reports ────────────────────────────────────────────────────

export const useFetchAnnualReports = () =>
  useMutation({
    mutationFn: ({ caseId, symbol, companyName }: { caseId: number; symbol: string; companyName?: string }) =>
      customFetch<{ ok: boolean; reportsFound: number; reports: unknown[] }>(`/api/cases/${caseId}/data-room/fetch-reports`, {
        method: "POST",
        body: JSON.stringify({ symbol, companyName }),
        headers: { "Content-Type": "application/json" },
      }),
  });

// ── POST run-research ─────────────────────────────────────────────────────

export const useRunResearch = () =>
  useMutation({
    mutationFn: ({ caseId }: { caseId: number }) =>
      customFetch<{ ok: boolean; newItems: number; totalItems: number }>(`/api/cases/${caseId}/data-room/run-research`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      }),
  });

// ── GET peers ─────────────────────────────────────────────────────────────

export const useGetPeers = (caseId: number) =>
  useQuery({
    queryKey: getPeersQueryKey(caseId),
    queryFn: () => customFetch<{ peers: Peer[] }>(`/api/cases/${caseId}/data-room/peers`),
    enabled: !!caseId,
  });

// ── PATCH peers ───────────────────────────────────────────────────────────

export const useUpdatePeers = () =>
  useMutation({
    mutationFn: ({ caseId, peers }: { caseId: number; peers: Peer[] }) =>
      customFetch<{ ok: boolean }>(`/api/cases/${caseId}/data-room/peers`, {
        method: "PATCH",
        body: JSON.stringify({ peers }),
        headers: { "Content-Type": "application/json" },
      }),
  });

// ── POST upload ───────────────────────────────────────────────────────────

export const useUploadDocument = () =>
  useMutation({
    mutationFn: ({ caseId, file, docType, fiscalYear, companyName }: {
      caseId: number;
      file: File;
      docType: string;
      fiscalYear?: string;
      companyName?: string;
    }) => {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("docType", docType);
      if (fiscalYear) formData.append("fiscalYear", fiscalYear);
      if (companyName) formData.append("companyName", companyName);
      return customFetch<CaseDocument>(`/api/cases/${caseId}/data-room/upload`, {
        method: "POST",
        body: formData,
      });
    },
  });

// ── DELETE document ───────────────────────────────────────────────────────

export const useDeleteDocument = () =>
  useMutation({
    mutationFn: ({ caseId, docId }: { caseId: number; docId: number }) =>
      customFetch<void>(`/api/cases/${caseId}/data-room/documents/${docId}`, { method: "DELETE" }),
  });

// ── POST organogram-tree ──────────────────────────────────────────────────

export const useSaveOrganogramTree = () =>
  useMutation({
    mutationFn: ({ caseId, tree, summary }: { caseId: number; tree: unknown[]; summary: string }) =>
      customFetch<{ ok: boolean }>(`/api/cases/${caseId}/data-room/organogram-tree`, {
        method: "POST",
        body: JSON.stringify({ tree, summary }),
        headers: { "Content-Type": "application/json" },
      }),
  });
